export const currency_list = [
  {
    icon: "",
    english_name: "Bitcoin",
    persian_name: "بیت کوین",
    symbol: "BTC",
    price: "$35,287.7",
    percent: "8-0.17%",
    isMain: true,
  },
  {
    icon: "",
    english_name: "Ethereum",
    persian_name: "اتریوم",
    symbol: "ETH",
    price: "$2,427.53",
    percent: "-0.08%",
    isMain: true,
  },
  {
    icon: "",
    english_name: "Tether",
    persian_name: "تتر",
    symbol: "USDT",
    price: "$1.00",
    percent: "0.01%",
    isMain: true,
  },
  {
    icon: "",
    english_name: "Binance Coin",
    persian_name: "بایننس کوین",
    symbol: "BNB",
    price: "$327.27",
    percent: "0.25%",
    isMain: false,
  },
  {
    icon: "",
    english_name: "Cardano",
    persian_name: "کاردانو",
    symbol: "ADA",
    price: "$1.49",
    percent: "0.00%",
    isMain: false,
  },
  {
    icon: "",
    english_name: "XRP",
    persian_name: "ریپل",
    symbol: "XRP",
    price: "$0.8758",
    percent: "0.02%",
    isMain: false,
  },
  {
    icon: "",
    english_name: "Dogecoin",
    persian_name: "داج کوین",
    symbol: "DOGE",
    price: "$0.3044",
    percent: "0.30%",
    isMain: false,
  },
  {
    icon: "",
    english_name: "Polkadot",
    persian_name: "پولکادوت",
    symbol: "DOT",
    price: "$21.11",
    percent: "1.34%",
    isMain: false,
  },
  {
    icon: "",
    english_name: "uniswap",
    persian_name: "یونی سواپ",
    symbol: "UNI",
    price: "$25.55",
    percent: "-0.61%",
    isMain: false,
  },
];
